---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-api-k8s-cloudfrosted-com-v1alpha1-configuration
  failurePolicy: Fail
  name: mconfiguration.kb.io
  rules:
  - apiGroups:
    - api.k8s.cloudfrosted.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-api-k8s-cloudfrosted-com-v1alpha1-configuration
  failurePolicy: Fail
  name: vconfiguration.kb.io
  rules:
  - apiGroups:
    - api.k8s.cloudfrosted.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurations
  sideEffects: None
