# permissions for end users to edit configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configuration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tutorial
    app.kubernetes.io/part-of: tutorial
    app.kubernetes.io/managed-by: kustomize
  name: configuration-editor-role
rules:
- apiGroups:
  - api.k8s.cloudfrosted.com
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.k8s.cloudfrosted.com
  resources:
  - configurations/status
  verbs:
  - get
